### ISSUE TITLE
[feat] 3주차 세미나 실습 과제

### ISSUE THREAD

**Issue by mmaybei** [AND-SOPT-iOS/KimSuyeon#5]
## 🛠 Issue

3주차 세미나 실습 과제

## 📝 To-do

- [x] 금융 페이지 구현
- [x] 인기 차트 페이지 구현
- [x] 메인 탭바 구현
